version: "3.8"

services:
    web-app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./service:/service
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASSWORD=dbuserpassword
        command: python manage.py runserver 0.0.0.0:8000

        depends_on:
            - database

    database:
        image: postgres:14.6-alpine
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbuserpassword

    redis:
        image: redis:7.0-alpine
        hostname: redis

    worker:
        build:
            context: .
        hostname: worker
        entrypoint: celery
        command: -A service worker --loglevel=INFO
        volumes:
            - ./service:/service
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASSWORD=dbuserpassword
        links:
            - redis
        depends_on:
            - redis
            - database

    flower:
        build:
            context: .
        hostname: flower
        ports:
            - "5555:5555"
        entrypoint: celery
        command: -A service flower
        volumes:
            - ./service:/service
        links:
            - redis
        depends_on:
            - redis
